export const TEAM_PLAN = [
  {
    role: "Founder / CEO (kamu)",
    headcount: 1,
    timing: "M0",
    stage: "✅ Active",
    expertise: "Product vision, fundraising, business",
    salaryRangeIdr: "40–60jt (often defer at pre-seed)",
  },
  {
    role: "Co-Founder / CTO",
    headcount: 1,
    timing: "M0–M3",
    stage: "🔍 Hiring",
    expertise: "Fullstack + system architecture (kandidat: ex-Tokopedia, Bukalapak senior eng)",
    salaryRangeIdr: "50–80jt + equity 15–25%",
  },
  {
    role: "Senior Fullstack Engineer",
    headcount: 2,
    timing: "M3–M6",
    stage: "🔍 Plan",
    expertise: "Next.js + TypeScript + Drizzle, financial product experience preferred",
    salaryRangeIdr: "35–45jt/orang",
  },
  {
    role: "Quant / Data Analyst",
    headcount: 1,
    timing: "M3",
    stage: "🔍 Plan",
    expertise: "Backtest engine, scoring algo tuning, regime classification",
    salaryRangeIdr: "35–55jt",
  },
  {
    role: "Product Designer",
    headcount: 1,
    timing: "M3",
    stage: "🔍 Plan",
    expertise: "Fintech UX, dense data visualization, mobile + desktop",
    salaryRangeIdr: "25–40jt",
  },
  {
    role: "Customer Success Lead",
    headcount: 1,
    timing: "M6",
    stage: "⚪ Plan",
    expertise: "Onboarding trader retail, content edukasi, manage Discord community",
    salaryRangeIdr: "15–25jt",
  },
  {
    role: "Content / Marketing",
    headcount: 1,
    timing: "M3",
    stage: "🔍 Plan",
    expertise: "Daily content saham, social media (X, Instagram, TikTok), SEO",
    salaryRangeIdr: "15–25jt",
  },
  {
    role: "Growth / Performance Marketing",
    headcount: 1,
    timing: "M6",
    stage: "⚪ Plan",
    expertise: "Meta Ads, Google Ads, attribution analytics",
    salaryRangeIdr: "25–40jt",
  },
  {
    role: "Compliance Officer (part-time)",
    headcount: 0.5,
    timing: "M6",
    stage: "⚪ Plan (legal counsel retainer)",
    expertise: "OJK regulasi, UU PDP, AML/PPATK",
    salaryRangeIdr: "Retainer 20–30jt/bln",
  },
  {
    role: "DevOps / SRE",
    headcount: 1,
    timing: "M9",
    stage: "⚪ Plan",
    expertise: "Kubernetes, infra-as-code, monitoring di scale",
    salaryRangeIdr: "30–45jt",
  },
];
